import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { supabase } from "../supabaseClient";
import { useEffect } from "react";
import { wrapInRetry } from "./call";
import KanyeSrc from "../assets/Kanye West.jpg";
import main from "../styles/main.module.css";

const Home: NextPage = () => {
  // const func = async () => {
  //   const { data } = await supabase.from("todos").select("*");
  //   console.log(data);
  // };

  // useEffect(() => {
  //   func();
  //
  // const getImport = async () => {
  //   const kanyeID = "5K4W6rqBFWDnAN6FQUkS6x";
  //   const kanyeImport = await import(`../JSON/${kanyeID}.json`, {
  //     assert: { type: "json" },
  //   });

  //   Object.entries(kanyeImport).forEach(([songName, songID]) => {
  //     if (songName !== "default") {
  //       console.log(songName, songID);
  //     }
  //   });
  // };
  // useEffect(() => {
  //   getImport();
  // }, []);

  // const songNames = [
  //   "Bound 2",
  //   "Father Stretch My Hands Pt. 1",
  //   "Praise God ",
  //   "I Love It",
  //   "Ni**as In Paris",
  //   "Moon",
  //   "Off The Grid",
  //   "Waves",
  //   "Yikes",
  //   "Gold Digger",
  //   "True Love",
  //   "Flashing Lights",
  //   "Mama",
  //   "Champions",
  //   "Ghost Town",
  //   "Fade",
  //   "All Day",
  //   "Ultralight Beam",
  //   "Believe What I Say",
  //   "Closed on Sunday",
  //   "No Child Left Behind",
  //   "No Mistakes",
  //   "Wash Us In The Blood",
  //   "Lift Yourself",
  //   "New Slaves",
  // ];
  // let kanyeObj = {};
  // const getTrackIds = async () => {
  //   songNames.forEach(async (songName) => {
  //     const res = await wrapInRetry(getArtist, `${songName}`);
  //     let songURI: any;
  //     if (res.tracks.items.length === 0) {
  //       songURI = "4Li2WHPkuyCdtmokzW2007";
  //     } else songURI = res.tracks.items[0].id;
  //     kanyeObj[songName] = songURI;
  //   });
  //   console.log(kanyeObj);
  // };
  // useEffect(() => {
  //   callArtist();
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Track Trivia</h1>

        <p className={styles.description}>Test your Music Knowledge</p>

        <div className={styles.grid}>
          <Link
            href={`/start/${encodeURIComponent("artists")}/${encodeURIComponent(
              "5K4W6rqBFWDnAN6FQUkS6x"
            )}`}
          >
            <div className={styles.card}>
              <img
                src={KanyeSrc.src}
                className={main.thumbnailImg}
                alt=""
              ></img>
              <h2>Kanye West &rarr;</h2>
              <h4>10 Questions</h4>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Written by Dawson Contreras
        </a>
      </footer>
    </div>
  );
};

export default Home;
